/* auto-generated by NAPI-RS */
/* eslint-disable */
/** An incoming session, before the application accepts it. */
export declare class IncomingSession {
  get path(): string
  get authority(): string
  get headers(): Array<JsHeader>
  /** Subprotocols the client offered, in preference order. */
  get protocols(): Array<string>
  /** Accepts the session. Can only be called once. */
  accept(): WebTransportSession
}

/** A listening WebTransport server. */
export declare class WebTransportServer {
  /**
   * Binds a server. Throws if the address is unavailable or the TLS material
   * cannot be parsed.
   *
   * Async because binding spawns the accept task, which needs the addon's
   * Tokio runtime to be entered; a sync napi call has no runtime context.
   */
  static bind(options: JsServerOptions): Promise<WebTransportServer>
  /** The port actually bound, resolving 0 to the ephemeral port chosen. */
  get port(): number
  /**
   * Resolves with the next connection-level failure, or null once the
   * server stops. These happen before a session exists, so they cannot be
   * reported on one.
   */
  nextError(): Promise<string | undefined | null>
  /**
   * Stops the server: closes the endpoint and ends both queues.
   *
   * Both `accept` and `next_error` park on a channel, and a JS `stop()` that
   * only set a flag left those promises pending for good. That keeps Bun's
   * event loop alive so the process never exits on its own, and leaves napi
   * calls outstanding when it is finally torn down, which aborts the
   * process. Closing the receivers resolves them to null, so the JS loops
   * end and the runtime can drain.
   */
  stop(): void
  /** Resolves with the next incoming session, or null once the server stops. */
  accept(): Promise<IncomingSession | undefined | null>
}

/** A connected WebTransport session, as seen from JS. */
export declare class WebTransportSession {
  /** The CONNECT stream id identifying this session. */
  get id(): bigint
  /** "pending" | "reliable-only" | "supports-unreliable". */
  get reliability(): string
  /**
   * Largest datagram payload that can be sent right now, or null when
   * datagrams are unavailable. Varies with the path MTU.
   */
  get maxDatagramSize(): number | null
  /** The subprotocol the server selected, or an empty string. */
  get protocol(): string
  /**
   * Headers from the server's CONNECT response, as name/value pairs.
   *
   * Empty for a server-side session, which never receives one.
   */
  get responseHeaders(): Array<Array<string>>
  get state(): string
  /**
   * Sends one datagram.
   *
   * Synchronous because it either fits the current window or fails at once;
   * there is nothing to await.
   */
  sendDatagram(payload: Uint8Array): void
  /**
   * Sends several datagrams in one call.
   *
   * A game server pushing tens of thousands of movement datagrams a second
   * pays the JS-to-native crossing per datagram; batching amortises it.
   * Oversized entries are skipped rather than failing the batch, matching
   * the unreliable semantics of a single send.
   */
  sendDatagrams(payloads: Array<Uint8Array>): number
  /**
   * Bytes currently queued for sending on this session.
   *
   * Applications use this for their own backpressure decisions (shedding
   * load for a client that has stopped keeping up), so it is a cheap
   * synchronous read rather than part of `getStats`.
   */
  get queuedBytes(): bigint
  /**
   * Inbound datagrams dropped because the receive queue was full.
   *
   * Non-zero under overload; the pattern of loss (steady vs bursty) tells an
   * application whether it is behind by a constant margin or just failing
   * to absorb spikes.
   */
  get datagramsDropped(): bigint
  /**
   * UDP datagrams the transport has received on this session's connection.
   *
   * Not in the spec; the transport-level counterpart of `datagramsDropped`.
   * Comparing the two locates loss: a gap means the network or socket
   * dropped packets; parity means an application-level queue did.
   */
  get udpPacketsReceived(): bigint
  /**
   * Resolves with the next inbound datagram, or null once the session ends.
   *
   * Returns owned bytes: the payload outlives the Rust buffer it arrived in.
   */
  recvDatagram(): Promise<Uint8Array | undefined | null>
  /**
   * Resolves with up to `max` inbound datagrams, or null once the session
   * ends.
   *
   * The async boundary costs a promise per call, so pulling datagrams one at
   * a time caps throughput far below what the transport delivers (the Rust
   * path sustains millions a second; per-datagram promises sustain
   * thousands). One call per batch amortises that crossing.
   */
  recvDatagrams(max: number): Promise<Array<Uint8Array> | undefined | null>
  /**
   * Switches inbound datagram delivery to a push pump.
   *
   * `callback` is invoked on the JS thread with batches of `Uint8Array`,
   * and once with an empty batch when the session ends. Push delivery
   * exists because even batched pulls still pay the promise machinery once
   * per batch per session: under many low-rate sessions that is once per
   * datagram, which saturates the JS thread long before the transport
   * does. A threadsafe function crosses into JS without a promise, so the
   * per-datagram cost becomes an ordinary stream enqueue.
   *
   * The pump applies backpressure in Rust: its queue holds 16 batches and
   * blocks when full, which fills the session's own bounded queue, which
   * drops the oldest datagram, so loss stays accounted for and bounded.
   */
  startDatagramPump(callback: () => unknown): void
  /**
   * Resolves when the session reaches a terminal state, reporting how it
   * ended. Backs the `closed` promise.
   */
  closed(): Promise<JsCloseInfo>
  /**
   * Resolves once the session begins draining. Backs the `draining` promise.
   *
   * Only `Draining` settles this. A session that closes without ever
   * draining leaves the promise pending for good, which is what the spec
   * asks for: `draining` reports that the session started winding down,
   * not that it ended.
   * Resolves `true` once the session drains, or `false` if it ends without
   * ever draining.
   *
   * It reports the outcome rather than staying pending on the second case:
   * a napi future that never settles holds its JS callback, and through it
   * the whole `WebTransport`, for the life of the process. The JS layer
   * leaves its own `draining` promise pending when this answers `false`,
   * which is what the spec asks for.
   */
  draining(): Promise<boolean>
  /**
   * Opens a unidirectional stream to the peer.
   *
   * `send_group` and `send_order` place the stream in the scheduler; the
   * order is a string so the full 64-bit range survives the JS boundary,
   * which cannot represent it as a number.
   */
  createUnidirectionalStream(sendGroup?: bigint | undefined | null, sendOrder?: bigint | undefined | null, waitUntilAvailable?: boolean | undefined | null): Promise<WtSendStream>
  /** Opens a bidirectional stream to the peer. */
  createBidirectionalStream(sendGroup?: bigint | undefined | null, sendOrder?: bigint | undefined | null, waitUntilAvailable?: boolean | undefined | null): Promise<WtBidiStream>
  /** Derives keying material bound to this session. */
  exportKeyingMaterial(label: Uint8Array, context: Uint8Array, length: number): Uint8Array
  /**
   * Connection statistics. Members the transport cannot source are absent
   * rather than zero.
   */
  getStats(): JsConnectionStats | null
  /**
   * Resolves with the next incoming unidirectional stream, or null once the
   * session ends.
   */
  acceptUnidirectionalStream(): Promise<WtRecvStream | undefined | null>
  /**
   * Resolves with the next incoming bidirectional stream, or null once the
   * session ends.
   */
  acceptBidirectionalStream(): Promise<WtBidiStream | undefined | null>
  close(info?: JsCloseInfo | undefined | null): void
  /**
   * Begins draining: the peer is told to stop opening new streams while
   * existing ones finish. Sends WT_DRAIN_SESSION on the CONNECT stream.
   */
  drain(): void
}

/** A bidirectional stream's two halves. */
export declare class WtBidiStream {
  get writable(): WtSendStream
  get readable(): WtRecvStream
}

/** The receive half of a WebTransport stream. */
export declare class WtRecvStream {
  /**
   * Reads the next chunk, or null at end of stream.
   *
   * `max` bounds the read so a BYOB reader asks for only what it can hold.
   */
  read(max?: number | undefined | null): Promise<Uint8Array | undefined | null>
  stop(code: number): Promise<undefined>
  get bytesRead(): bigint
}

/** The send half of a WebTransport stream. */
export declare class WtSendStream {
  /**
   * Writes a chunk, resolving once the transport has accepted all of it.
   *
   * The pending promise is what gives the JS WritableStream real
   * backpressure: it stays unresolved while the flow-control window is full.
   */
  write(chunk: Uint8Array): Promise<undefined>
  /**
   * Writes only what fits the current flow-control window, returning how
   * many bytes were accepted. Backs `atomicWrite`.
   */
  writeSome(chunk: Uint8Array): Promise<number>
  finish(): Promise<undefined>
  reset(code: number): Promise<undefined>
  /**
   * Resolves with the peer's error code once it stops reading, or null if
   * the stream ended without one.
   */
  stopped(): Promise<number | undefined | null>
  get bytesWritten(): bigint
  setPriority(priority: number): Promise<undefined>
  /** The scheduler id, so send group and order can be changed later. */
  get schedulerId(): bigint | null
  /** Moves this stream into a different send group, or the null group. */
  setSendGroup(group?: bigint | undefined | null): void
  /**
   * Changes this stream's send order. `null` withdraws it from strict
   * ordering, leaving it to share its group's turn.
   */
  setSendOrder(sendOrder?: bigint | undefined | null): void
}

/**
 * Closes every QUIC endpoint, then blocks briefly while the runtime settles
 * the fallout: parked `accept`s, `read`s and `closed` waiters complete and
 * their promises resolve before the environment goes away.
 *
 * Called synchronously from the JS `exit` event, which fires before teardown
 * begins. Blocking there is safe, since nothing else needs the JS thread, and it
 * is exactly what lets everything parked on the endpoints drain in time,
 * rather than being torn down mid-flight.
 *
 * The wait is bounded and only paid when there was something to close.
 */
export declare function closeAllEndpoints(): void

/** Opens a WebTransport session. Resolves once the session is established. */
export declare function connect(url: string, options?: JsClientOptions | undefined | null): Promise<WebTransportSession>

export declare function generateSelfSigned(hostnames: Array<string>): SelfSignedCert

/**
 * Closes every QUIC endpoint before the runtime that drives them goes away.
 *
 * napi owns the Tokio runtime the endpoint drivers run on and shuts it down
 * at process exit. A driver still live at that moment is dropped mid-flight
 * and the process aborts: the run succeeds, then dies, which a shell reports
 * only as a non-zero exit with nothing pointing at the cause.
 *
 * Called once by the JS layer as it loads. A `#[module_exports]` hook would
 * register this without the JS side knowing, but that macro sits behind
 * napi-rs's compat mode and the async entry points cannot take an `Env`.
 * Repeat calls are no-ops.
 */
export declare function installExitHook(): void

export interface JsCertHash {
  algorithm: string
  value: Uint8Array
}

/** Options accepted by `connect`, mirroring `WebTransportOptions`. */
export interface JsClientOptions {
  /** Certificate hashes as `{ algorithm, value }`, where value is a byte array. */
  serverCertificateHashes?: Array<JsCertHash>
  headers?: Array<JsHeader>
  protocols?: Array<string>
  requireUnreliable?: boolean
  /** "default" | "throughput" | "low-latency". */
  congestionControl?: string
  /**
   * Share a QUIC connection with other sessions to the same origin. The JS
   * layer rejects this alongside certificate hashes before it reaches here.
   */
  allowPooling?: boolean
}

/** How a session ended. */
export interface JsCloseInfo {
  closeCode: number
  reason: string
}

/** Connection statistics that the transport can actually report. */
export interface JsConnectionStats {
  bytesSent: bigint
  bytesReceived: bigint
  packetsSent: bigint
  packetsReceived: bigint
  packetsLost: bigint
  bytesLost: bigint
  /** Milliseconds. */
  smoothedRtt: number
  /** Milliseconds. */
  minRtt: number
  congestionWindow: bigint
}

export interface JsHeader {
  name: string
  value: string
}

export interface JsServerOptions {
  port: number
  host?: string
  /** PEM certificate chain. */
  cert: string
  /** PEM private key. */
  key: string
  maxSessions?: number
  /**
   * Concurrent QUIC streams per direction, per connection. Reserved
   * bookkeeping scales with this, so it trades headroom against memory.
   */
  maxConcurrentStreams?: number
}

/**
 * Generates a self-signed certificate for local development, returning the PEM
 * pair and the SHA-256 hash a client passes as `serverCertificateHashes`.
 */
export interface SelfSignedCert {
  cert: string
  key: string
  hash: Uint8Array
}
